Repository unagisoftware/afip-invoices, pull requests merged in 2021-09, with the labels that each got.

#3 Add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#4 Add contribute message in README
  README.md
Labels: documentation

#5 Add rubocop and coverage badges in README
  .github/workflows/rspec.yml
  Gemfile
  Gemfile.lock
  README.md
  spec/spec_helper.rb
Labels: enhancement

#7 Fix notes PDF generation
  app/pdfs/invoice_pdf.rb
  spec/controllers/v1/invoices_controller_spec.rb
  spec/factories/invoices.rb
  spec/support/responses/bill_types_response.xml
Labels: bug
